language: go
env:
  jobs:
    - TEST_SUITE=tests
    - TEST_SUITE=linters

before_install:
  - go get -v -t ./...

script: |
  set -x
  case $TEST_SUITE in
  tests)
      ./.travis/tests.sh
      ;;
  linters)
      ./.travis/linters.sh
      ;;
  *)
      echo "[!] Unknown test suite: ${TEST_SUITE}. Exiting."
      exit 1
  esac

after_success:
  - bash <(curl -s https://codecov.io/bash)
