version: 2.1

orbs:
  go: circleci/go@0.2.0

environment:
  CGO_ENABLED: "0"

jobs:
  linters:
    working_directory: /go/src/github.com/facebook/time
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - run: sudo apt-get install libpcap-dev
      - run: go get -v -t ./...
      - run: .circleci/linters.sh


workflows:
  main:
   jobs:
     - linters
