name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: sudo apt-get install libpcap-dev
      - run: go build -v ./...
      - run: go test -v -race -coverprofile=coverage.txt ./...
      # fuzzing, need to specify each package separately
      - run: go test -v -fuzz='.*' -fuzztime=10s ./ptp/protocol/
      - run: go test -v -fuzz='.*' -fuzztime=10s ./ntp/protocol/
      - run: go test -v -fuzz='.*' -fuzztime=10s ./ntp/chrony/
      - uses: codecov/codecov-action@v2
